controller:
  args:
    appResyncPeriod: 30

server:
  service:
    type: NodePort
    nodePortHttp: 30000
  additionalApplications:
    - name: applications
      namespace: argo
      project: default
      destination:
        server: https://kubernetes.default.svc
      project: default
      source:
        path: app-of-apps
        repoURL: https://github.com/ItsKev/multi-environment-gitops
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

configs:
  repositories:
    github:
      url: https://github.com/ItsKev/multi-environment-gitops