apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-stage
  namespace: argo
spec:
  destination:
    namespace: stage
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/nginx/stage
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true