apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: dev
spec:
  destination:
    namespace: dev
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/nginx/dev
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}